title: Isaac's Blog
author: Isaac Hwang
description: Where I put my musings.

highlighter: null
permalink: /:title

url:
baseurl:

color_scheme: amber

#
plugins:
  - jekyll-gravatar
#

# Custom options:
# color_scheme: azul|ruby|amber|avocado
# color_scheme: avocado
